### ISSUE TITLE
Quantum Chess date

### ISSUE THREAD

**Issue by cantwellc** [HuangJunye/Awesome-Quantum-Games#7]
Hey, great list. I just wanted  update the date for Quantum Chess. The playable prototype, seen in [Anyone Can Quantum](https://www.youtube.com/watch?v=Hi0BzqV_b44), was available in 2015. The public early access launched in 2016 on Steam. 2017 is just the listed "final release" date on Steam, but it was available to play much earlier.

**Comment by HuangJunye** [comment]
@cantwellc Hi Chris, thanks for sharing the history of quantum chess and correcting the date! I am a big fan of yours! Hope we can play quantum chess together one day :)

**Comment by HuangJunye** [comment]
Fixed by #8
